import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Rajdhani } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/partials/navbar'
import Footer from '@/components/partials/footer'

const inter = Inter({ subsets: ['latin'] })
const rajdhani = Rajdhani({ 
  subsets: ['latin'], 
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${rajdhani.className} max-w-screen-2xl mx-auto`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
